const TechnologiesMock: Technologies = {
    core: {
        title: "core",
        desc: "The core technologies I utilise everyday + Typescript for type safety.",
        images: [
            {
                title: "HTML5",
                image: "https://temiloluwa-p.vercel.app/_next/image?url=%2FHTML5.png&w=64&q=75",
            },
            {
                title: "CSS3",
                image: "https://temiloluwa-p.vercel.app/_next/image?url=%2FCSS3.png&w=64&q=75",
            },
            {
                title: "Javascript",
                image: "https://temiloluwa-p.vercel.app/javascript.svg",
            },
            {
                title: "Typescript",
                image: "https://temiloluwa-p.vercel.app/_next/image?url=%2FCSS3.png&w=64&q=75",
            },
        ],
    },
    frontend: {
        title: "Frontend",
        desc: "The technologies I use when making frontend apps.",
        images: [
            {
                title: "Reactjs",
                image: "/images/svgs/frontend/react-svgrepo-com.svg",
            },
            {
                title: "Vuejs",
                image: "/images/svgs/frontend/vue-svgrepo-com.svg",
            },
            {
                title: "TailwindCss",
                image: "/images/svgs/frontend/tailwind-svgrepo-com.svg",
            },
            {
                title: "Nextjs",
                image: "/images/svgs/frontend/nextjs-svgrepo-com.svg",
            },
        ],
    },
    backend: {
        title: "Backend",
        desc: "The technologies I use when dealing with projects that require server side logic.",
        images: [
            {
                title: "Firebase",
                image: "/images/svgs/backend/firebase-svgrepo-com.svg",
            },
            {
                title: "Nodejs",
                image: "/images/svgs/backend/nodejs-icon-svgrepo-com.svg",
            },
            {
                title: "Nestjs",
                image: "/images/svgs/backend/nestjs-svgrepo-com.svg",
            },
        ],
    },
    other: {
        title: "DeskTop&Mobile",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam, voluptatem. ",
        images: [
            {
                title: "Tauri",
                image: "/images/svgs/desktopAndMobile/eS928FcHOR1gPMhOZDS3Dxx_G1grDvV_q-aSXrvTFBg.webp",
            },
            {
                title: "Flutter",
                image: "/images/svgs/desktopAndMobile/flutter-svgrepo-com.svg",
            },
            {
                title: "ReactNative",
                image: "/images/svgs/desktopAndMobile/react-svgrepo-com.svg",
            },
        ],
    },
};

export { TechnologiesMock };

// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface Technologies {
    core: Backend;
    frontend: Backend;
    backend: Backend;
    other: Backend;
}

export interface Backend {
    title: string;
    desc: string;
    images: Image[];
}

export interface Image {
    title: string;
    image: string;
}
